services:
  app:
    build:
      context: ./backend
      dockerfile: src/Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: "postgresql://admin:password@database:5432/senior_checkin"
      PYTHONPATH: /app/src
    depends_on:
      - database
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - app

  database:
    image: "postgres:15"
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: senior_checkin 
    
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  database-test:
    image: "postgres:15"
    ports:
      - 52000:5432

    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: senior_checkin_test 
    
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data: