services:
  app:
    build:
      context: ./backend
      dockerfile: src/Dockerfile
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: "postgresql://admin:password@database:5432/senior_checkin"
    depends_on:
      - database
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  database:
    image: "postgres:15"
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: senior_checkin 
    
    volumes:
      - ./db-data/:/var/lib/postgresql/data/